insert into public.card_templates (
  slug,
  name,
  description,
  rarity,
  card_type,
  attack,
  health,
  size,
  aura,
  image_url,
  flavor_text,
  ability_data,
  balance_version
)
values
  (
    'garrett-current',
    'Garrett (Current)',
    'My name is Garrett and I love being woke.',
    'COMMON',
    'CHARACTER',
    4,
    2,
    1,
    0,
    '/card-art/garrett-current.webp',
    'I love smoking weed and being a liberal sheep.',
    '[{"id":"garrett-current-do-weed","label":"Do Weed","trigger":"START_OF_TURN","effects":[{"type":"HEAL","target":"SELF","amount":1}]}]'::jsonb,
    'prototype-0.1'
  ),
  (
    'garrett-prime',
    'Garrett (Prime)',
    'My name is Garrett and I love going to the gym and being a good guy.',
    'LEGENDARY',
    'LEADER',
    8,
    10,
    2,
    10,
    '/card-art/garrett-prime.webp',
    'Flex on these people because the summer shred was completed.',
    '[{"id":"garrett-prime-flex","label":"Flex","trigger":"ACTIVATED","requiresTarget":true,"effects":[{"type":"DAMAGE","target":"ENEMY_CHARACTER","amount":4},{"type":"BLIND","target":"ENEMY_CHARACTER","amount":1,"duration":"TURN"}]}]'::jsonb,
    'prototype-0.1'
  ),
  (
    'rowletforsenator',
    'RowletForSenator',
    'I love being Nicholas and dating Indian women.',
    'RARE',
    'CHARACTER',
    5,
    7,
    5,
    4,
    '/card-art/rowletforsenator.webp',
    'I love studying in Florida.',
    '[{"id":"rowletforsenator-study","label":"Studying for College","trigger":"START_OF_TURN","effects":[{"type":"BUFF_SIZE","target":"SELF","amount":-1,"duration":"PERMANENT"},{"type":"BUFF_ATTACK","target":"SELF","amount":1,"duration":"PERMANENT"}]}]'::jsonb,
    'prototype-0.1'
  ),
  ('mwyi', 'mwyi', '', 'RARE', 'CHARACTER', 0, 0, 0, 0, '/card-art/mwyi.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('necrp', 'necrp', '', 'RARE', 'CHARACTER', 0, 0, 0, 0, '/card-art/necrp.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('necrp-tuff-edition', 'necrp (tuff edition)', 'necrp, but locked in and way more tuff.', 'DIVINE', 'LEADER', 12, 15, 4, 12, '/card-art/necrp-tuff-edition.webp', 'Same necrp. Heavier aura.', '[{"id":"necrp-tuff-board-wipe","label":"Tuff Sweep","trigger":"ACTIVATED","requiresTarget":false,"cooldownTurns":3,"effects":[{"type":"DAMAGE","target":"ENEMY_BOARD_CHARACTERS","amount":8}]}]'::jsonb, 'prototype-0.1'),
  ('anarchy', 'Anarchy', '', 'EPIC', 'CHARACTER', 0, 0, 0, 0, '/card-art/anarchy.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('buurazu', 'buurazu', '', 'MYTHIC', 'CHARACTER', 0, 0, 0, 0, '/card-art/buurazu.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('jpj', 'jpj', '', 'LEGENDARY', 'CHARACTER', 0, 0, 0, 0, '/card-art/jpj.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('tyler-robinson', 'Tyler Robinson', 'A narrow counter card that only has a job when Charlie Kirk is on the board.', 'COMMON', 'CHARACTER', 2, 1, 1, 1, '/card-art/tyler-robinson.webp', 'Built for exactly one matchup.', '[{"id":"tyler-robinson-only-counter","label":"Only Counter","trigger":"ACTIVATED","requiresTarget":true,"effects":[{"type":"DESTROY","target":"ENEMY_CHARACTER","cardSlug":"charlie-kirk"},{"type":"DESTROY","target":"SELF"}]}]'::jsonb, 'prototype-0.1'),
  ('charlie-kirk', 'Charlie Kirk', '', 'EPIC', 'CHARACTER', 0, 0, 0, 0, '/card-art/charlie-kirk.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('ada-printa', 'ada printa', '', 'COMMON', 'CHARACTER', 0, 0, 0, 0, '/card-art/ada-printa.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('eth22', 'eth22', '', 'RARE', 'CHARACTER', 0, 0, 0, 0, '/card-art/eth22.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('frenchplaty', 'frenchplaty', '', 'RARE', 'CHARACTER', 0, 0, 0, 0, '/card-art/frenchplaty.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('tweeku', 'tweeku', '', 'RARE', 'CHARACTER', 0, 0, 0, 0, '/card-art/tweeku.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('mwyi-inactive', 'mwyi (inactive)', '', 'MYTHIC', 'CHARACTER', 0, 0, 0, 0, '/card-art/mwyi-inactive.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('vanessa', 'Vanessa', '', 'EPIC', 'CHARACTER', 0, 0, 0, 0, '/card-art/vanessa.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('the1nutbandit', 'the1nutbandit', '', 'ULTRA_LEGENDARY', 'CHARACTER', 0, 0, 0, 0, '/card-art/the1nutbandit.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('pacmanpowerghost', 'pacmanpowerghost', '', 'RARE', 'CHARACTER', 0, 0, 0, 0, '/card-art/pacmanpowerghost.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('kyu-sugardust', 'Kyu Sugardust', '', 'COMMON', 'CHARACTER', 0, 0, 0, 0, '/card-art/kyu-sugardust.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('benjamin-netanyahu', 'Benjamin Netanyahu', '', 'COMMON', 'CHARACTER', 0, 0, 0, 0, '/card-art/benjamin-netanyahu.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('tahm-kench', 'Tahm Kench', '', 'COMMON', 'CHARACTER', 0, 0, 0, 0, '/card-art/tahm-kench.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('necrps-drunken-dad', 'necrps drunken dad', '', 'MYTHIC', 'CHARACTER', 0, 0, 0, 0, '/card-art/necrps-drunken-dad.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('gabriela-stein', 'Gabriela Stein', 'Rare, steady, and aggressively mid.', 'RARE', 'CHARACTER', 4, 4, 3, 3, '/card-art/gabriela-stein.webp', 'Nothing crazy, nothing useless.', '[]'::jsonb, 'prototype-0.1'),
  ('the-group-chat', 'the Group Chat', '', 'RARE', 'BUILDING', 0, 0, 0, 0, '/card-art/the-group-chat.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('hunie-pop-speedrunning', 'Hunie Pop Speedrunning', '', 'COMMON', 'BUILDING', 0, 0, 0, 0, '/card-art/hunie-pop-speedrunning.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('huniepotheads', 'HuniePotHeads', '', 'RARE', 'BUILDING', 0, 0, 0, 0, '/card-art/huniepotheads.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('poland', 'Poland', '', 'EPIC', 'BUILDING', 0, 0, 0, 0, '/card-art/poland.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('florida', 'Florida', '', 'EPIC', 'BUILDING', 0, 0, 0, 0, '/card-art/florida.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('texas', 'Texas', '', 'EPIC', 'BUILDING', 0, 0, 0, 0, '/card-art/texas.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('jpjs-basement', 'jpjs Basement', '', 'MYTHIC', 'BUILDING', 0, 0, 0, 0, '/card-art/jpjs-basement.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('white-monster', 'White Monster', '', 'RARE', 'ITEM', 0, 0, 0, 0, '/card-art/white-monster.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('the-bong', 'The Bong', '', 'LEGENDARY', 'ITEM', 0, 0, 0, 0, '/card-art/the-bong.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('assault-rifle', 'assault rifle', '', 'EPIC', 'ITEM', 0, 0, 0, 0, '/card-art/assault-rifle.webp', '', '[]'::jsonb, 'prototype-0.1'),
  ('zubr-beer', 'zubr beer', '', 'MYTHIC', 'ITEM', 0, 0, 0, 0, '/card-art/zubr-beer.webp', '', '[]'::jsonb, 'prototype-0.1')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  rarity = excluded.rarity,
  card_type = excluded.card_type,
  attack = excluded.attack,
  health = excluded.health,
  size = excluded.size,
  aura = excluded.aura,
  image_url = excluded.image_url,
  flavor_text = excluded.flavor_text,
  ability_data = excluded.ability_data,
  balance_version = excluded.balance_version;
