import type { CardTemplate } from "@/types/cards";

function zeroStatCard(
  slug: string,
  name: string,
  rarity: CardTemplate["rarity"],
  cardType: CardTemplate["cardType"],
  category?: string,
): CardTemplate {
  return {
    slug,
    name,
    description: "",
    flavorText: "",
    rarity,
    cardType,
    attack: 0,
    health: 0,
    size: 0,
    aura: 0,
    category,
    imageUrl: `/card-art/${slug}.webp`,
    abilityData: [],
  };
}

export const cardCatalog: CardTemplate[] = [
  {
    slug: "garrett-current",
    name: "Garrett (Current)",
    description: "My name is Garrett and I love being woke.",
    flavorText: "I love smoking weed and being a liberal sheep.",
    rarity: "COMMON",
    cardType: "CHARACTER",
    attack: 4,
    health: 2,
    size: 1,
    aura: 0,
    imageUrl: "/card-art/garrett-current.webp",
    abilityData: [
      {
        id: "garrett-current-do-weed",
        label: "Do Weed",
        trigger: "START_OF_TURN",
        effects: [{ type: "HEAL", target: "SELF", amount: 1 }],
      },
    ],
  },
  {
    slug: "garrett-prime",
    name: "Garrett (Prime)",
    description: "My name is Garrett and I love going to the gym and being a good guy.",
    flavorText: "Flex on these people because the summer shred was completed.",
    rarity: "LEGENDARY",
    cardType: "LEADER",
    attack: 8,
    health: 10,
    size: 2,
    aura: 10,
    category: "BASED",
    imageUrl: "/card-art/garrett-prime.webp",
    abilityData: [
      {
        id: "garrett-prime-flex",
        label: "Flex",
        trigger: "ACTIVATED",
        requiresTarget: true,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 4 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  {
    slug: "rowletforsenator",
    name: "RowletForSenator",
    description: "I love being Nicholas and dating Indian women.",
    flavorText: "I love studying in Florida.",
    rarity: "RARE",
    cardType: "CHARACTER",
    attack: 5,
    health: 7,
    size: 5,
    aura: 4,
    category: "AMERICAN",
    imageUrl: "/card-art/rowletforsenator.webp",
    abilityData: [
      {
        id: "rowletforsenator-study",
        label: "Studying for College",
        trigger: "START_OF_TURN",
        effects: [
          { type: "BUFF_SIZE", target: "SELF", amount: -1, duration: "PERMANENT" },
          { type: "BUFF_ATTACK", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  zeroStatCard("mwyi", "mwyi", "RARE", "CHARACTER", "MINOR"),
  zeroStatCard("necrp", "necrp", "RARE", "CHARACTER"),
  {
    slug: "necrp-tuff-edition",
    name: "necrp (tuff edition)",
    description: "necrp, but locked in and way more tuff.",
    flavorText: "Same necrp. Heavier aura.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 12,
    health: 15,
    size: 4,
    aura: 12,
    imageUrl: "/card-art/necrp-tuff-edition.webp",
    abilityData: [
      {
        id: "necrp-tuff-board-wipe",
        label: "Tuff Sweep",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "DAMAGE", target: "ENEMY_BOARD_CHARACTERS", amount: 8 },
        ],
      },
    ],
  },
  {
    slug: "pillow-necrp",
    name: "pillow necrp",
    description: "necrp but tucked in and basically unkillable. the whole enemy team is fighting a pillow fort and losing morale every turn.",
    flavorText: "\"YES!! \"",
    rarity: "DIVINE",
    cardType: "BUILDING",
    attack: 0,
    health: 50,
    size: 9,
    aura: 12,
    imageUrl: "/card-art/cards/pillow-necrp.webp",
    abilityData: [
      {
        id: "pillow-necrp-full-rest",
        label: "Full Rest",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "HEAL", target: "SELF", amount: 999 },
        ],
      },
    ],
  },
  zeroStatCard("anarchy", "Anarchy", "EPIC", "CHARACTER"),
  zeroStatCard("buurazu", "buurazu", "MYTHIC", "CHARACTER"),
  zeroStatCard("jpj", "jpj", "LEGENDARY", "CHARACTER"),
  {
    slug: "tyler-robinson",
    name: "Tyler Robinson",
    description: "A narrow counter card that only has a job when Charlie Kirk is on the board.",
    flavorText: "Built for exactly one matchup.",
    rarity: "COMMON",
    cardType: "CHARACTER",
    attack: 2,
    health: 1,
    size: 1,
    aura: 1,
    category: "AMERICAN",
    imageUrl: "/card-art/tyler-robinson.webp",
    abilityData: [
      {
        id: "tyler-robinson-only-counter",
        label: "Only Counter",
        trigger: "ACTIVATED",
        requiresTarget: true,
        effects: [
          { type: "DESTROY", target: "ENEMY_CHARACTER", cardSlug: "charlie-kirk" },
          { type: "DESTROY", target: "SELF" },
        ],
      },
    ],
  },
  zeroStatCard("charlie-kirk", "Charlie Kirk", "EPIC", "CHARACTER", "AMERICAN"),
  zeroStatCard("ada-printa", "ada printa", "COMMON", "CHARACTER"),
  zeroStatCard("eth22", "eth22", "RARE", "CHARACTER"),
  zeroStatCard("frenchplaty", "frenchplaty", "RARE", "CHARACTER"),
  zeroStatCard("tweeku", "tweeku", "RARE", "CHARACTER"),
  zeroStatCard("mwyi-inactive", "mwyi (inactive)", "MYTHIC", "CHARACTER"),
  zeroStatCard("vanessa", "Vanessa", "EPIC", "CHARACTER", "AMERICAN"),
  zeroStatCard("the1nutbandit", "the1nutbandit", "ULTRA_LEGENDARY", "CHARACTER"),
  zeroStatCard("pacmanpowerghost", "pacmanpowerghost", "RARE", "CHARACTER"),
  zeroStatCard("kyu-sugardust", "Kyu Sugardust", "COMMON", "CHARACTER"),
  zeroStatCard("benjamin-netanyahu", "Benjamin Netanyahu", "COMMON", "CHARACTER"),
  zeroStatCard("tahm-kench", "Tahm Kench", "COMMON", "CHARACTER"),
  zeroStatCard("necrps-drunken-dad", "necrps drunken dad", "MYTHIC", "CHARACTER", "BASED"),
  {
    slug: "gabriela-stein",
    name: "Gabriela Stein",
    description: "Rare, steady, and aggressively mid.",
    flavorText: "Nothing crazy, nothing useless.",
    rarity: "RARE",
    cardType: "CHARACTER",
    attack: 4,
    health: 4,
    size: 3,
    aura: 3,
    imageUrl: "/card-art/gabriela-stein.webp",
    abilityData: [],
  },
  zeroStatCard("the-group-chat", "the Group Chat", "RARE", "BUILDING"),
  zeroStatCard("hunie-pop-speedrunning", "Hunie Pop Speedrunning", "COMMON", "BUILDING"),
  zeroStatCard("huniepotheads", "HuniePotHeads", "RARE", "BUILDING"),
  zeroStatCard("poland", "Poland", "EPIC", "BUILDING"),
  zeroStatCard("florida", "Florida", "EPIC", "BUILDING", "AMERICAN"),
  zeroStatCard("texas", "Texas", "EPIC", "BUILDING", "AMERICAN"),
  zeroStatCard("jpjs-basement", "jpjs Basement", "MYTHIC", "BUILDING"),
  zeroStatCard("white-monster", "White Monster", "RARE", "ITEM", "BASED"),
  zeroStatCard("the-bong", "The Bong", "LEGENDARY", "ITEM", "AMERICAN"),
  zeroStatCard("assault-rifle", "assault rifle", "EPIC", "ITEM", "AMERICAN"),
  zeroStatCard("zubr-beer", "zubr beer", "MYTHIC", "ITEM", "BASED"),
];

export function getCardBySlug(slug: string) {
  return cardCatalog.find((card) => card.slug === slug);
}
