import type { CardTemplate } from "@/types/cards";

function zeroStatCard(
  slug: string,
  name: string,
  rarity: CardTemplate["rarity"],
  cardType: CardTemplate["cardType"],
  category?: string,
): CardTemplate {
  return {
    slug,
    name,
    description: "",
    flavorText: "",
    rarity,
    cardType,
    attack: 0,
    health: 0,
    size: 0,
    aura: 0,
    category,
    imageUrl: `/card-art/${slug}.webp`,
    abilityData: [],
  };
}

const supabaseCardArtBase = "https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards";
const supabaseSoundBase = "https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds";

export const cardCatalog: CardTemplate[] = [
  {
    slug: "garrett-current",
    name: "Garrett (Current)",
    description: "My name is Garrett and I love being woke.",
    flavorText: "I love smoking weed and being a liberal sheep.",
    rarity: "COMMON",
    cardType: "CHARACTER",
    attack: 4,
    health: 2,
    size: 1,
    aura: 0,
    imageUrl: "/card-art/garrett-current.webp",
    abilityData: [
      {
        id: "garrett-current-do-weed",
        label: "Do Weed",
        trigger: "START_OF_TURN",
        effects: [{ type: "HEAL", target: "SELF", amount: 1 }],
      },
    ],
  },
  {
    slug: "garrett-prime",
    name: "Garrett (Prime)",
    description: "My name is Garrett and I love going to the gym and being a good guy.",
    flavorText: "Flex on these people because the summer shred was completed.",
    rarity: "LEGENDARY",
    cardType: "LEADER",
    attack: 8,
    health: 10,
    size: 2,
    aura: 10,
    category: "BASED",
    imageUrl: "/card-art/garrett-prime.webp",
    abilityData: [
      {
        id: "garrett-prime-flex",
        label: "Flex",
        trigger: "ACTIVATED",
        requiresTarget: true,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 4 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  {
    slug: "rowletforsenator",
    name: "RowletForSenator",
    description: "I love being Nicholas and dating Indian women.",
    flavorText: "I love studying in Florida.",
    rarity: "RARE",
    cardType: "CHARACTER",
    attack: 5,
    health: 7,
    size: 5,
    aura: 4,
    category: "AMERICAN",
    imageUrl: "/card-art/rowletforsenator.webp",
    abilityData: [
      {
        id: "rowletforsenator-study",
        label: "Studying for College",
        trigger: "START_OF_TURN",
        effects: [
          { type: "BUFF_SIZE", target: "SELF", amount: -1, duration: "PERMANENT" },
          { type: "BUFF_ATTACK", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "rowletforsenator-evil",
    name: "RowletForSenator (Evil)",
    description: "RowletForSenator after the campaign trail got corrupted and the study arc went fully sinister.",
    flavorText: "Still studying. Different syllabus.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 10,
    health: 12,
    size: 5,
    aura: 9,
    category: "AMERICAN",
    traits: ["AMERICAN", "CONTROL", "AGGRESSIVE"],
    imageUrl: `${supabaseCardArtBase}/rowletforsenator.webp`,
    soundEffectUrl: `${supabaseSoundBase}/rowletforsenator.mp3`,
    dropEnabled: true,
    abilityData: [
      {
        id: "rowletforsenator-evil-opposition-research",
        label: "Opposition Research",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 5 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  zeroStatCard("mwyi", "mwyi", "RARE", "CHARACTER", "MINOR"),
  zeroStatCard("necrp", "necrp", "RARE", "CHARACTER"),
  {
    slug: "andrew-tate",
    name: "Andrew Tate",
    description: "A loud DIVINE leader built around pressure, ego, and turning every board state into a sales pitch.",
    flavorText: "Top G energy, bottom-tier humility.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 11,
    health: 13,
    size: 5,
    aura: 12,
    category: "CONTROVERSIAL",
    traits: ["AGGRESSIVE", "CONTROL", "CONTROVERSIAL"],
    imageUrl: `${supabaseCardArtBase}/andrew-tate.webp`,
    soundEffectUrl: `${supabaseSoundBase}/andrew-tate.mp3`,
    dropEnabled: true,
    abilityData: [
      {
        id: "andrew-tate-matrix-pressure",
        label: "Matrix Pressure",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 6 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
          { type: "BUFF_ATTACK", target: "SELF", amount: 1, duration: "PERMANENT" },
          { type: "BUFF_AURA", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "tristan-tate",
    name: "Tristan Tate",
    description: "A DIVINE support character who makes the leader harder to remove while acting like the whole table is beneath him.",
    flavorText: "Second brother, first-class nuisance.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 7,
    health: 9,
    size: 4,
    aura: 10,
    category: "CONTROVERSIAL",
    traits: ["SUPPORT", "CONTROVERSIAL", "COMBO_PIECE"],
    imageUrl: `${supabaseCardArtBase}/tristan-tate.webp`,
    soundEffectUrl: `${supabaseSoundBase}/tristan-tate.mp3`,
    dropEnabled: true,
    abilityData: [
      {
        id: "tristan-tate-brother-buffer",
        label: "Brother Buffer",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "HEAL", target: "FRIENDLY_LEADER", amount: 8 },
          { type: "SHIELD", target: "FRIENDLY_LEADER" },
          { type: "BUFF_AURA", target: "FRIENDLY_LEADER", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "necrp-tuff-edition",
    name: "necrp (tuff edition)",
    description: "necrp, but locked in and way more tuff.",
    flavorText: "Same necrp. Heavier aura.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 12,
    health: 15,
    size: 4,
    aura: 12,
    imageUrl: "/card-art/necrp-tuff-edition.webp",
    abilityData: [
      {
        id: "necrp-tuff-board-wipe",
        label: "Tuff Sweep",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "DAMAGE", target: "ENEMY_BOARD_CHARACTERS", amount: 8 },
        ],
      },
    ],
  },
  {
    slug: "pillow-necrp",
    name: "pillow necrp",
    description: "necrp but tucked in and basically unkillable. the whole enemy team is fighting a pillow fort and losing morale every turn.",
    flavorText: "\"YES!! \"",
    rarity: "DIVINE",
    cardType: "BUILDING",
    attack: 0,
    health: 50,
    size: 9,
    aura: 12,
    category: "MINOR",
    traits: ["MINOR", "SUPPORT", "TANK"],
    imageUrl: "/card-art/cards/pillow-necrp.webp",
    abilityData: [
      {
        id: "pillow-necrp-full-rest",
        label: "Full Rest",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "HEAL", target: "SELF", amount: 999 },
        ],
      },
      {
        id: "pillow-necrp-nap-circle",
        label: "Nap Circle",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "HEAL", target: "FRIENDLY_BOARD_CHARACTERS", amount: 8 },
        ],
      },
    ],
  },
  {
    slug: "gay-little-puppygirl-story-leader",
    name: "gay Little puppygirl (Story Leader)",
    description: "A story-only boss leader version of gay Little puppygirl.",
    flavorText: "tiny bark, catastrophic consequences.",
    rarity: "MYTHIC",
    cardType: "LEADER",
    attack: 8,
    health: 16,
    size: 5,
    aura: 9,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/gay-little-puppygirl.webp`,
    soundEffectUrl: `${supabaseSoundBase}/gay-little-puppygirl.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "gay-little-puppygirl-woke-mind-virus",
        label: "Woke Mind Virus",
        trigger: "ACTIVATED",
        oncePerGame: true,
        requiresTarget: false,
        effects: [
          {
            type: "COIN_FLIP",
            target: "SELF",
            metadata: {
              heads: [
                {
                  type: "COIN_FLIP",
                  target: "SELF",
                  metadata: {
                    heads: [{ type: "DESTROY", target: "ENEMY_CHARACTER" }],
                    tails: [],
                  },
                },
              ],
              tails: [],
            },
          },
        ],
      },
    ],
  },
  {
    slug: "buurazu-story-leader",
    name: "buurazu (Story Leader)",
    description: "A story-only boss leader version of buurazu.",
    flavorText: "The pressure gets worse the longer this goes.",
    rarity: "MYTHIC",
    cardType: "LEADER",
    attack: 7,
    health: 20,
    size: 7,
    aura: 10,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/buurazu.webp`,
    soundEffectUrl: `${supabaseSoundBase}/buurazu.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "buurazu-story-mythic-pressure",
        label: "Mythic Pressure",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "BUFF_ATTACK", target: "SELF", amount: 2, duration: "PERMANENT" },
          { type: "BUFF_HEALTH", target: "SELF", amount: 3, duration: "PERMANENT" },
          { type: "BUFF_AURA", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "anarchy-story-leader",
    name: "Anarchy (Story Leader)",
    description: "A story-only boss leader version of Anarchy.",
    flavorText: "\"my lawyer took away my food stamps\"",
    rarity: "LEGENDARY",
    cardType: "LEADER",
    attack: 8,
    health: 24,
    size: 8,
    aura: 10,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/anarchy.webp`,
    soundEffectUrl: `${supabaseSoundBase}/anarchy.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "anarchy-story-ban-my-opps",
        label: "Ban My Opps",
        trigger: "ACTIVATED",
        oncePerGame: true,
        requiresTarget: false,
        effects: [{ type: "DESTROY", target: "RANDOM_ENEMY_CHARACTER" }],
      },
    ],
  },
  {
    slug: "pacmanpowerghost-corrupted-story-leader",
    name: "pacmanpowerghost (corrupted)",
    description: "A story-only corrupted boss leader version of pacmanpowerghost.",
    flavorText: "The ghost came back wrong.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 10,
    health: 32,
    size: 7,
    aura: 11,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/pacmanpowerghost.webp`,
    soundEffectUrl: `${supabaseSoundBase}/pacmanpowerghost.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "pacmanpowerghost-corrupted-haunt",
        label: "Corrupted Haunt",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 5 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  {
    slug: "gay-little-puppygirl-story-reward",
    name: "gay Little puppygirl (Story Reward)",
    description: "A story reward character version of gay Little puppygirl.",
    flavorText: "A smaller version of the boss bite.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 7,
    health: 6,
    size: 4,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/gay-little-puppygirl.webp`,
    soundEffectUrl: `${supabaseSoundBase}/gay-little-puppygirl.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "buurazu-story-reward",
    name: "buurazu (Story Reward)",
    description: "A story reward character version of buurazu.",
    flavorText: "Still heavy, just not boss-heavy.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 4,
    health: 8,
    size: 5,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/buurazu.webp`,
    soundEffectUrl: `${supabaseSoundBase}/buurazu.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "anarchy-story-reward",
    name: "Anarchy (Story Reward)",
    description: "A story reward character version of Anarchy.",
    flavorText: "A controlled dose of chaos.",
    rarity: "EPIC",
    cardType: "CHARACTER",
    attack: 5,
    health: 7,
    size: 5,
    aura: 5,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/anarchy.webp`,
    soundEffectUrl: `${supabaseSoundBase}/anarchy.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "pacmanpowerghost-corrupted-story-reward",
    name: "pacmanpowerghost (corrupted reward)",
    description: "A story reward character version of corrupted pacmanpowerghost.",
    flavorText: "A ghost you actually get to keep.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 6,
    health: 7,
    size: 4,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/pacmanpowerghost.webp`,
    soundEffectUrl: `${supabaseSoundBase}/pacmanpowerghost.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "ada-printa-chapter-2-leader",
    name: "Ada Printa (Chapter 2 Leader)",
    description: "A story-only leader version of Ada Printa.",
    flavorText: "Printer warmed up. Bad sign.",
    rarity: "EPIC",
    cardType: "LEADER",
    attack: 9,
    health: 16,
    size: 5,
    aura: 9,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/ada-printa.webp`,
    soundEffectUrl: `${supabaseSoundBase}/ada-printa.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "eth22-chapter-2-leader",
    name: "eth22 (Chapter 2 Leader)",
    description: "A story-only leader version of eth22.",
    flavorText: "The second path gets uglier.",
    rarity: "MYTHIC",
    cardType: "LEADER",
    attack: 10,
    health: 20,
    size: 5,
    aura: 10,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/eth22.webp`,
    soundEffectUrl: `${supabaseSoundBase}/eth22.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "mwyi-corrupted-chapter-2-leader",
    name: "mwyi (corrupted)",
    description: "A story-only corrupted leader version of mwyi.",
    flavorText: "The 50/50 stopped being funny.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 11,
    health: 26,
    size: 6,
    aura: 11,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/mwyi.webp`,
    soundEffectUrl: `${supabaseSoundBase}/mwyi.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "vanessa-chapter-2-leader",
    name: "Vanessa (Chapter 2 Leader)",
    description: "A story-only leader version of Vanessa.",
    flavorText: "Heartbreak became a win condition.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 12,
    health: 32,
    size: 7,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/vanessa.webp`,
    soundEffectUrl: `${supabaseSoundBase}/vanessa.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "tom-macdonald-blacked-chapter-2-leader",
    name: "Tom MacDonald (Blacked)",
    description: "A story-only leader guarding the last stretch before the ascended Woke Mind Virus.",
    flavorText: "The gate before the rematch got louder.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 13,
    health: 36,
    size: 7,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/tom-macdonald.webp`,
    soundEffectUrl: `${supabaseSoundBase}/tom-macdonald.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "woke-mind-virus-ascended-story-leader",
    name: "The Woke Mind Virus (Ascended)",
    description: "A stronger rematch version of the final boss.",
    flavorText: "It learned from the first loss.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 14,
    health: 42,
    size: 8,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/woke-mind-virus.webp`,
    soundEffectUrl: `${supabaseSoundBase}/woke-mind-virus.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "woke-mind-virus-total-brainrot",
        label: "Total Brainrot",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_BOARD_CHARACTERS", amount: 7 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
          { type: "BUFF_ATTACK", target: "SELF", amount: 2, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "ada-printa-chapter-2-reward",
    name: "Ada Printa (Chapter 2 Reward)",
    description: "A story reward character version of Ada Printa.",
    flavorText: "Still printing problems.",
    rarity: "EPIC",
    cardType: "CHARACTER",
    attack: 5,
    health: 5,
    size: 3,
    aura: 4,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/ada-printa.webp`,
    soundEffectUrl: `${supabaseSoundBase}/ada-printa.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "eth22-chapter-2-reward",
    name: "eth22 (Chapter 2 Reward)",
    description: "A story reward character version of eth22.",
    flavorText: "Reduced from boss threat to deck problem.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 8,
    health: 6,
    size: 4,
    aura: 5,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/eth22.webp`,
    soundEffectUrl: `${supabaseSoundBase}/eth22.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "mwyi-corrupted-chapter-2-reward",
    name: "mwyi (corrupted reward)",
    description: "A story reward character version of corrupted mwyi.",
    flavorText: "You probably should not keep this, but you can.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 9,
    health: 8,
    size: 5,
    aura: 7,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/mwyi.webp`,
    soundEffectUrl: `${supabaseSoundBase}/mwyi.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "vanessa-chapter-2-reward",
    name: "Vanessa (Chapter 2 Reward)",
    description: "A story reward character version of Vanessa.",
    flavorText: "A little less boss, still a lot.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 8,
    health: 10,
    size: 6,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/vanessa.webp`,
    soundEffectUrl: `${supabaseSoundBase}/vanessa.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "tom-macdonald-blacked-chapter-2-reward",
    name: "Tom MacDonald (Blacked Reward)",
    description: "A story reward character version of Tom MacDonald (Blacked).",
    flavorText: "Less boss fight, still a warning shot.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 9,
    health: 11,
    size: 5,
    aura: 7,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/tom-macdonald.webp`,
    soundEffectUrl: `${supabaseSoundBase}/tom-macdonald.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "woke-mind-virus-deployable",
    name: "Woke Mind Virus (Deployable)",
    description: "A risky global item that empowers every friendly card currently in play.",
    flavorText: "Power, with a tiny chance of catastrophic brainrot.",
    rarity: "DIVINE",
    cardType: "ITEM",
    attack: 0,
    health: 0,
    size: 0,
    aura: 0,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/woke-mind-virus.webp`,
    soundEffectUrl: `${supabaseSoundBase}/woke-mind-virus.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "woke-mind-virus-deploy",
        label: "Deploy Brainrot",
        trigger: "ON_PLAY",
        requiresTarget: false,
        effects: [
          { type: "BUFF_ATTACK", target: "FRIENDLY_BOARD_AND_LEADER", amount: 2, duration: "PERMANENT" },
          { type: "BUFF_HEALTH", target: "FRIENDLY_BOARD_AND_LEADER", amount: 4, duration: "PERMANENT" },
          { type: "BUFF_AURA", target: "FRIENDLY_BOARD_AND_LEADER", amount: 2, duration: "PERMANENT" },
          { type: "CHANCE_DESTROY", target: "FRIENDLY_BOARD_AND_LEADER", chance: 0.05 },
        ],
      },
    ],
  },
  {
    slug: "woke-charlie-kirk-chapter-3-leader",
    name: "Woke Charlie Kirk",
    description: "A story-only leader version of Charlie Kirk after the algorithm got to him.",
    flavorText: "The talking points started talking back.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 13,
    health: 44,
    size: 8,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/woke-charlie-kirk-chapter-3-leader.webp`,
    soundEffectUrl: `${supabaseSoundBase}/woke-charlie-kirk-chapter-3-leader.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "woke-charlie-kirk-platform-shift",
        label: "Platform Shift",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "DAMAGE", target: "ENEMY_BOARD_CHARACTERS", amount: 3 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
          { type: "BUFF_AURA", target: "SELF", amount: 2, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "king-von-chapter-3-leader",
    name: "King Von",
    description: "A story-only leader with direct pressure and a heavier deck behind him.",
    flavorText: "Chapter 3 stopped warming up.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 14,
    health: 46,
    size: 8,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/king-von-chapter-3-leader.webp`,
    soundEffectUrl: `${supabaseSoundBase}/king-von-chapter-3-leader.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "king-von-pressure-story",
        label: "Story Pressure",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 8 },
          { type: "BUFF_ATTACK", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "shrekel-not-in-poland-chapter-3-leader",
    name: "Shrekel (not in Poland)",
    description: "A story-only leader that is explicitly not in Poland and still somehow a problem.",
    flavorText: "Wrong swamp. Correct danger.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 14,
    health: 48,
    size: 9,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/shrekel-not-in-poland-chapter-3-leader.webp`,
    soundEffectUrl: `${supabaseSoundBase}/shrekel-not-in-poland-chapter-3-leader.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "shrekel-not-in-poland-swamp-tax",
        label: "Swamp Tax",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "HEAL", target: "SELF", amount: 10 },
          { type: "SHIELD", target: "SELF" },
          { type: "STUN", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  {
    slug: "kanye-west-chapter-3-leader",
    name: "Kanye West",
    description: "A story-only leader who can briefly become YE, then pays for the crash after.",
    flavorText: "One round of genius. Then the invoice.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 12,
    health: 45,
    size: 7,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/kanye-west-chapter-3-leader.webp`,
    soundEffectUrl: `${supabaseSoundBase}/kanye-west-chapter-3-leader.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "kanye-west-become-ye",
        label: "Become YE",
        trigger: "ACTIVATED",
        requiresTarget: false,
        oncePerGame: true,
        effects: [
          {
            type: "TEMP_TRANSFORM",
            target: "SELF",
            metadata: {
              ownerTurns: 1,
              attack: 8,
              health: 15,
              aura: 3,
              afterAttack: -3,
              afterHealth: -8,
              afterAura: -1,
            },
          },
        ],
      },
    ],
  },
  {
    slug: "suicide-bomber-chapter-3-leader",
    name: "Suicide Bomber",
    description: "A story-only leader that detonates once when it survives at critical health.",
    flavorText: "The board state becomes a crater.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 8,
    health: 50,
    size: 9,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/suicide-bomber-chapter-3-leader.webp`,
    soundEffectUrl: `${supabaseSoundBase}/suicide-bomber-chapter-3-leader.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "suicide-bomber-critical-detonation",
        label: "Critical Detonation",
        trigger: "ON_DAMAGED",
        oncePerGame: true,
        requiresTarget: false,
        conditions: [{ type: "SELF_HEALTH_BELOW", value: 20 }],
        effects: [{ type: "DESTROY", target: "ALL_IN_PLAY_EXCEPT_SELF" }],
      },
    ],
  },
  {
    slug: "anarchy-gluttonous-chapter-3-leader",
    name: "Anarchy (Gluttonous)",
    description: "Anarchy, but even fatter. A final boss that eats board cards to become harder to kill.",
    flavorText: "The buffet fought back and lost.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 15,
    health: 62,
    size: 10,
    aura: 12,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/anarchy-gluttonous-chapter-3-leader.webp`,
    soundEffectUrl: `${supabaseSoundBase}/anarchy-gluttonous-chapter-3-leader.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "anarchy-gluttonous-devour",
        label: "Devour",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 3,
        effects: [{ type: "CONSUME", target: "ENEMY_BOARD_CARD" }],
      },
    ],
  },
  {
    slug: "necrps-very-drunken-dad",
    name: "necrps very drunken dad",
    description: "A story-only support card that makes late Chapter 3 decks less polite.",
    flavorText: "Somehow even more hammered.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 11,
    health: 18,
    size: 9,
    aura: 10,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/necrps-very-drunken-dad.webp`,
    soundEffectUrl: `${supabaseSoundBase}/necrps-very-drunken-dad.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "woke-charlie-kirk-chapter-3-reward",
    name: "Woke Charlie Kirk (Chapter 3 Reward)",
    description: "A story reward character version of Woke Charlie Kirk.",
    flavorText: "A smaller contradiction.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 8,
    health: 8,
    size: 4,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/woke-charlie-kirk-chapter-3-reward.webp`,
    soundEffectUrl: `${supabaseSoundBase}/woke-charlie-kirk-chapter-3-reward.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "king-von-chapter-3-reward",
    name: "King Von (Chapter 3 Reward)",
    description: "A story reward character version of King Von.",
    flavorText: "Lower stakes. Still pressure.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 9,
    health: 9,
    size: 5,
    aura: 7,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/king-von-chapter-3-reward.webp`,
    soundEffectUrl: `${supabaseSoundBase}/king-von-chapter-3-reward.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "shrekel-not-in-poland-chapter-3-reward",
    name: "Shrekel (not in Poland Reward)",
    description: "A story reward character version of Shrekel.",
    flavorText: "Still not in Poland.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 8,
    health: 12,
    size: 6,
    aura: 7,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/shrekel-not-in-poland-chapter-3-reward.webp`,
    soundEffectUrl: `${supabaseSoundBase}/shrekel-not-in-poland-chapter-3-reward.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "kanye-west-chapter-3-reward",
    name: "Kanye West (Chapter 3 Reward)",
    description: "A story reward character version of Kanye West.",
    flavorText: "The crash is still included.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 8,
    health: 8,
    size: 4,
    aura: 7,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/kanye-west-chapter-3-reward.webp`,
    soundEffectUrl: `${supabaseSoundBase}/kanye-west-chapter-3-reward.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "suicide-bomber-chapter-3-reward",
    name: "Suicide Bomber (Chapter 3 Reward)",
    description: "A story reward character version of Suicide Bomber.",
    flavorText: "Less blast radius. Still suspicious.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 7,
    health: 10,
    size: 5,
    aura: 7,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/suicide-bomber-chapter-3-reward.webp`,
    soundEffectUrl: `${supabaseSoundBase}/suicide-bomber-chapter-3-reward.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "anarchy-gluttonous-chapter-3-reward",
    name: "Anarchy (Gluttonous Reward)",
    description: "A story reward character version of Anarchy (Gluttonous).",
    flavorText: "Still hungry, but playable.",
    rarity: "DIVINE",
    cardType: "CHARACTER",
    attack: 10,
    health: 13,
    size: 6,
    aura: 8,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/anarchy-gluttonous-chapter-3-reward.webp`,
    soundEffectUrl: `${supabaseSoundBase}/anarchy-gluttonous-chapter-3-reward.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  zeroStatCard("anarchy", "Anarchy", "EPIC", "CHARACTER"),
  zeroStatCard("buurazu", "buurazu", "MYTHIC", "CHARACTER"),
  zeroStatCard("jpj", "jpj", "LEGENDARY", "CHARACTER"),
  {
    slug: "tyler-robinson",
    name: "Tyler Robinson",
    description: "A narrow counter card that only has a job when Charlie Kirk is on the board.",
    flavorText: "Built for exactly one matchup.",
    rarity: "COMMON",
    cardType: "CHARACTER",
    attack: 2,
    health: 1,
    size: 1,
    aura: 1,
    category: "AMERICAN",
    imageUrl: "/card-art/tyler-robinson.webp",
    abilityData: [
      {
        id: "tyler-robinson-only-counter",
        label: "Only Counter",
        trigger: "ACTIVATED",
        requiresTarget: true,
        effects: [
          { type: "DESTROY", target: "ENEMY_CHARACTER", cardSlug: "charlie-kirk" },
          { type: "DESTROY", target: "SELF" },
        ],
      },
    ],
  },
  zeroStatCard("charlie-kirk", "Charlie Kirk", "EPIC", "CHARACTER", "AMERICAN"),
  {
    slug: "zed",
    name: "Zed",
    description: "The shadow assassin enters as a high-pressure finisher with blind and scaling damage.",
    flavorText: "The shadows already chose a target.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 8,
    health: 6,
    size: 4,
    aura: 8,
    category: "ASSASSIN",
    traits: ["AGGRESSIVE", "CONTROL", "ASSASSIN"],
    imageUrl: `${supabaseCardArtBase}/zed.webp`,
    soundEffectUrl: `${supabaseSoundBase}/zed.mp3`,
    dropEnabled: true,
    abilityData: [
      {
        id: "zed-shadow-mark",
        label: "Shadow Mark",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 7 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
          { type: "BUFF_ATTACK", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  zeroStatCard("ada-printa", "ada printa", "COMMON", "CHARACTER"),
  zeroStatCard("eth22", "eth22", "RARE", "CHARACTER"),
  zeroStatCard("frenchplaty", "frenchplaty", "RARE", "CHARACTER"),
  zeroStatCard("tweeku", "tweeku", "RARE", "CHARACTER"),
  zeroStatCard("mwyi-inactive", "mwyi (inactive)", "MYTHIC", "CHARACTER"),
  {
    ...zeroStatCard("vanessa", "Vanessa", "EPIC", "CHARACTER", "AMERICAN"),
    abilityData: [
      {
        id: "vanessa-heartbroken",
        label: "Heartbroken",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        conditions: [
          { type: "LEADER_IS", cardSlugs: ["garrett-current", "garrett-prime"] },
        ],
        effects: [
          { type: "BUFF_ATTACK", target: "SELF", amount: 3, duration: "PERMANENT" },
        ],
      },
    ],
  },
  zeroStatCard("the1nutbandit", "the1nutbandit", "ULTRA_LEGENDARY", "CHARACTER"),
  zeroStatCard("pacmanpowerghost", "pacmanpowerghost", "RARE", "CHARACTER"),
  zeroStatCard("kyu-sugardust", "Kyu Sugardust", "COMMON", "CHARACTER"),
  zeroStatCard("benjamin-netanyahu", "Benjamin Netanyahu", "COMMON", "CHARACTER"),
  zeroStatCard("tahm-kench", "Tahm Kench", "COMMON", "CHARACTER"),
  zeroStatCard("necrps-drunken-dad", "necrps drunken dad", "MYTHIC", "CHARACTER", "BASED"),
  {
    slug: "gabriela-stein",
    name: "Gabriela Stein",
    description: "Rare, steady, and aggressively mid.",
    flavorText: "Nothing crazy, nothing useless.",
    rarity: "RARE",
    cardType: "CHARACTER",
    attack: 4,
    health: 4,
    size: 3,
    aura: 3,
    imageUrl: "/card-art/gabriela-stein.webp",
    abilityData: [],
  },
  {
    ...zeroStatCard("the-group-chat", "the Group Chat", "RARE", "BUILDING", "BASED"),
    attack: 5,
    health: 10,
    size: 3,
    aura: 6,
    traits: ["BASED", "SUPPORT", "TANK"],
    abilityData: [
      {
        id: "the-group-chat-hype-cycle",
        label: "Hype Cycle",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 2,
        effects: [{ type: "BUFF_ATTACK", target: "FRIENDLY_BOARD_CHARACTERS", amount: 1, duration: "PERMANENT" }],
      },
    ],
  },
  {
    ...zeroStatCard("hunie-pop-speedrunning", "Hunie Pop Speedrunning", "COMMON", "BUILDING", "BASED"),
    attack: 1,
    health: 5,
    size: 3,
    aura: 0,
    traits: ["BASED", "SUPPORT"],
    abilityData: [
      {
        id: "hunie-pop-speedrunning-reset-route",
        label: "Reset Route",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [{ type: "HEAL", target: "FRIENDLY_CHARACTER", amount: 4 }],
      },
    ],
  },
  {
    ...zeroStatCard("huniepotheads", "HuniePotHeads", "RARE", "BUILDING", "PEDOPHILE"),
    attack: 0,
    health: 3,
    size: 4,
    aura: 5,
    traits: ["PEDOPHILE", "SUPPORT"],
    abilityData: [
      {
        id: "huniepotheads-smoke-screen",
        label: "Smoke Screen",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [{ type: "SHIELD", target: "FRIENDLY_CHARACTER" }],
      },
    ],
  },
  {
    ...zeroStatCard("poland", "Poland", "EPIC", "BUILDING", "BASED"),
    attack: 3,
    health: 23,
    size: 7,
    aura: 5,
    traits: ["BASED", "SUPPORT", "TANK"],
    abilityData: [
      {
        id: "poland-fortify-line",
        label: "Fortify Line",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [{ type: "BUFF_HEALTH", target: "FRIENDLY_BOARD_CHARACTERS", amount: 2, duration: "PERMANENT" }],
      },
    ],
  },
  {
    ...zeroStatCard("florida", "Florida", "EPIC", "BUILDING", "AMERICAN"),
    attack: 3,
    health: 15,
    size: 7,
    aura: 3,
    traits: ["AMERICAN", "SUPPORT", "TANK"],
    abilityData: [
      {
        id: "florida-chaos-boost",
        label: "Chaos Boost",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "BUFF_ATTACK", target: "FRIENDLY_CHARACTER", amount: 2, duration: "PERMANENT" },
          { type: "BUFF_AURA", target: "FRIENDLY_CHARACTER", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    ...zeroStatCard("texas", "Texas", "EPIC", "BUILDING", "AMERICAN"),
    attack: 4,
    health: 15,
    size: 7,
    aura: 4,
    traits: ["AMERICAN", "SUPPORT", "TANK"],
    abilityData: [
      {
        id: "texas-stand-your-ground",
        label: "Stand Your Ground",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "SHIELD", target: "FRIENDLY_CHARACTER" },
          { type: "BUFF_ATTACK", target: "FRIENDLY_CHARACTER", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    ...zeroStatCard("jpjs-basement", "jpjs Basement", "MYTHIC", "BUILDING"),
    attack: 8,
    health: 23,
    size: 9,
    aura: 9,
    category: "PEDOPHILE",
    traits: ["PEDOPHILE", "SUPPORT", "TANK"],
    abilityData: [
      {
        id: "jpjs-basement-trap",
        label: "Trap",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 3,
        conditions: [
          { type: "CARD_IN_HAND", cardSlug: "jpj" },
        ],
        effects: [
          { type: "STUN", target: "ENEMY_CHARACTER", amount: 3, duration: "TURN" },
        ],
      },
      {
        id: "jpjs-basement-lock-the-door",
        label: "Lock the Door",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "SHIELD", target: "FRIENDLY_LEADER" },
          { type: "HEAL", target: "FRIENDLY_LEADER", amount: 3 },
        ],
      },
    ],
  },
  zeroStatCard("white-monster", "White Monster", "RARE", "ITEM", "BASED"),
  zeroStatCard("the-bong", "The Bong", "LEGENDARY", "ITEM", "AMERICAN"),
  zeroStatCard("assault-rifle", "assault rifle", "EPIC", "ITEM", "AMERICAN"),
  zeroStatCard("zubr-beer", "zubr beer", "MYTHIC", "ITEM", "BASED"),
];

export function getCardBySlug(slug: string) {
  return cardCatalog.find((card) => card.slug === slug);
}
