import type { CardTemplate } from "@/types/cards";

function zeroStatCard(
  slug: string,
  name: string,
  rarity: CardTemplate["rarity"],
  cardType: CardTemplate["cardType"],
  category?: string,
): CardTemplate {
  return {
    slug,
    name,
    description: "",
    flavorText: "",
    rarity,
    cardType,
    attack: 0,
    health: 0,
    size: 0,
    aura: 0,
    category,
    imageUrl: `/card-art/${slug}.webp`,
    abilityData: [],
  };
}

const supabaseCardArtBase = "https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards";
const supabaseSoundBase = "https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds";

export const cardCatalog: CardTemplate[] = [
  {
    slug: "garrett-current",
    name: "Garrett (Current)",
    description: "My name is Garrett and I love being woke.",
    flavorText: "I love smoking weed and being a liberal sheep.",
    rarity: "COMMON",
    cardType: "CHARACTER",
    attack: 4,
    health: 2,
    size: 1,
    aura: 0,
    imageUrl: "/card-art/garrett-current.webp",
    abilityData: [
      {
        id: "garrett-current-do-weed",
        label: "Do Weed",
        trigger: "START_OF_TURN",
        effects: [{ type: "HEAL", target: "SELF", amount: 1 }],
      },
    ],
  },
  {
    slug: "garrett-prime",
    name: "Garrett (Prime)",
    description: "My name is Garrett and I love going to the gym and being a good guy.",
    flavorText: "Flex on these people because the summer shred was completed.",
    rarity: "LEGENDARY",
    cardType: "LEADER",
    attack: 8,
    health: 10,
    size: 2,
    aura: 10,
    category: "BASED",
    imageUrl: "/card-art/garrett-prime.webp",
    abilityData: [
      {
        id: "garrett-prime-flex",
        label: "Flex",
        trigger: "ACTIVATED",
        requiresTarget: true,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 4 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  {
    slug: "rowletforsenator",
    name: "RowletForSenator",
    description: "I love being Nicholas and dating Indian women.",
    flavorText: "I love studying in Florida.",
    rarity: "RARE",
    cardType: "CHARACTER",
    attack: 5,
    health: 7,
    size: 5,
    aura: 4,
    category: "AMERICAN",
    imageUrl: "/card-art/rowletforsenator.webp",
    abilityData: [
      {
        id: "rowletforsenator-study",
        label: "Studying for College",
        trigger: "START_OF_TURN",
        effects: [
          { type: "BUFF_SIZE", target: "SELF", amount: -1, duration: "PERMANENT" },
          { type: "BUFF_ATTACK", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  zeroStatCard("mwyi", "mwyi", "RARE", "CHARACTER", "MINOR"),
  zeroStatCard("necrp", "necrp", "RARE", "CHARACTER"),
  {
    slug: "necrp-tuff-edition",
    name: "necrp (tuff edition)",
    description: "necrp, but locked in and way more tuff.",
    flavorText: "Same necrp. Heavier aura.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 12,
    health: 15,
    size: 4,
    aura: 12,
    imageUrl: "/card-art/necrp-tuff-edition.webp",
    abilityData: [
      {
        id: "necrp-tuff-board-wipe",
        label: "Tuff Sweep",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "DAMAGE", target: "ENEMY_BOARD_CHARACTERS", amount: 8 },
        ],
      },
    ],
  },
  {
    slug: "pillow-necrp",
    name: "pillow necrp",
    description: "necrp but tucked in and basically unkillable. the whole enemy team is fighting a pillow fort and losing morale every turn.",
    flavorText: "\"YES!! \"",
    rarity: "DIVINE",
    cardType: "BUILDING",
    attack: 0,
    health: 50,
    size: 9,
    aura: 12,
    imageUrl: "/card-art/cards/pillow-necrp.webp",
    abilityData: [
      {
        id: "pillow-necrp-full-rest",
        label: "Full Rest",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "HEAL", target: "SELF", amount: 999 },
        ],
      },
    ],
  },
  {
    slug: "gay-little-puppygirl-story-leader",
    name: "gay Little puppygirl (Story Leader)",
    description: "A story-only boss leader version of gay Little puppygirl.",
    flavorText: "tiny bark, catastrophic consequences.",
    rarity: "MYTHIC",
    cardType: "LEADER",
    attack: 8,
    health: 16,
    size: 5,
    aura: 9,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/gay-little-puppygirl.webp`,
    soundEffectUrl: `${supabaseSoundBase}/gay-little-puppygirl.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "gay-little-puppygirl-woke-mind-virus",
        label: "Woke Mind Virus",
        trigger: "ACTIVATED",
        oncePerGame: true,
        requiresTarget: false,
        effects: [
          {
            type: "COIN_FLIP",
            target: "SELF",
            metadata: {
              heads: [
                {
                  type: "COIN_FLIP",
                  target: "SELF",
                  metadata: {
                    heads: [{ type: "DESTROY", target: "ENEMY_CHARACTER" }],
                    tails: [],
                  },
                },
              ],
              tails: [],
            },
          },
        ],
      },
    ],
  },
  {
    slug: "buurazu-story-leader",
    name: "buurazu (Story Leader)",
    description: "A story-only boss leader version of buurazu.",
    flavorText: "The pressure gets worse the longer this goes.",
    rarity: "MYTHIC",
    cardType: "LEADER",
    attack: 7,
    health: 20,
    size: 7,
    aura: 10,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/buurazu.webp`,
    soundEffectUrl: `${supabaseSoundBase}/buurazu.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "buurazu-story-mythic-pressure",
        label: "Mythic Pressure",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        effects: [
          { type: "BUFF_ATTACK", target: "SELF", amount: 2, duration: "PERMANENT" },
          { type: "BUFF_HEALTH", target: "SELF", amount: 3, duration: "PERMANENT" },
          { type: "BUFF_AURA", target: "SELF", amount: 1, duration: "PERMANENT" },
        ],
      },
    ],
  },
  {
    slug: "anarchy-story-leader",
    name: "Anarchy (Story Leader)",
    description: "A story-only boss leader version of Anarchy.",
    flavorText: "\"my lawyer took away my food stamps\"",
    rarity: "LEGENDARY",
    cardType: "LEADER",
    attack: 8,
    health: 24,
    size: 8,
    aura: 10,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/anarchy.webp`,
    soundEffectUrl: `${supabaseSoundBase}/anarchy.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "anarchy-story-ban-my-opps",
        label: "Ban My Opps",
        trigger: "ACTIVATED",
        oncePerGame: true,
        requiresTarget: false,
        effects: [{ type: "DESTROY", target: "RANDOM_ENEMY_CHARACTER" }],
      },
    ],
  },
  {
    slug: "pacmanpowerghost-corrupted-story-leader",
    name: "pacmanpowerghost (corrupted)",
    description: "A story-only corrupted boss leader version of pacmanpowerghost.",
    flavorText: "The ghost came back wrong.",
    rarity: "DIVINE",
    cardType: "LEADER",
    attack: 10,
    health: 32,
    size: 7,
    aura: 11,
    category: "STORY_BOSS",
    imageUrl: `${supabaseCardArtBase}/pacmanpowerghost.webp`,
    soundEffectUrl: `${supabaseSoundBase}/pacmanpowerghost.mp3`,
    dropEnabled: false,
    abilityData: [
      {
        id: "pacmanpowerghost-corrupted-haunt",
        label: "Corrupted Haunt",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 2,
        effects: [
          { type: "DAMAGE", target: "ENEMY_CHARACTER", amount: 5 },
          { type: "BLIND", target: "ENEMY_CHARACTER", amount: 1, duration: "TURN" },
        ],
      },
    ],
  },
  {
    slug: "gay-little-puppygirl-story-reward",
    name: "gay Little puppygirl (Story Reward)",
    description: "A story reward character version of gay Little puppygirl.",
    flavorText: "A smaller version of the boss bite.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 7,
    health: 6,
    size: 4,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/gay-little-puppygirl.webp`,
    soundEffectUrl: `${supabaseSoundBase}/gay-little-puppygirl.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "buurazu-story-reward",
    name: "buurazu (Story Reward)",
    description: "A story reward character version of buurazu.",
    flavorText: "Still heavy, just not boss-heavy.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 4,
    health: 8,
    size: 5,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/buurazu.webp`,
    soundEffectUrl: `${supabaseSoundBase}/buurazu.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "anarchy-story-reward",
    name: "Anarchy (Story Reward)",
    description: "A story reward character version of Anarchy.",
    flavorText: "A controlled dose of chaos.",
    rarity: "EPIC",
    cardType: "CHARACTER",
    attack: 5,
    health: 7,
    size: 5,
    aura: 5,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/anarchy.webp`,
    soundEffectUrl: `${supabaseSoundBase}/anarchy.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  {
    slug: "pacmanpowerghost-corrupted-story-reward",
    name: "pacmanpowerghost (corrupted reward)",
    description: "A story reward character version of corrupted pacmanpowerghost.",
    flavorText: "A ghost you actually get to keep.",
    rarity: "MYTHIC",
    cardType: "CHARACTER",
    attack: 6,
    health: 7,
    size: 4,
    aura: 6,
    category: "STORY_REWARD",
    imageUrl: `${supabaseCardArtBase}/pacmanpowerghost.webp`,
    soundEffectUrl: `${supabaseSoundBase}/pacmanpowerghost.mp3`,
    dropEnabled: false,
    abilityData: [],
  },
  zeroStatCard("anarchy", "Anarchy", "EPIC", "CHARACTER"),
  zeroStatCard("buurazu", "buurazu", "MYTHIC", "CHARACTER"),
  zeroStatCard("jpj", "jpj", "LEGENDARY", "CHARACTER"),
  {
    slug: "tyler-robinson",
    name: "Tyler Robinson",
    description: "A narrow counter card that only has a job when Charlie Kirk is on the board.",
    flavorText: "Built for exactly one matchup.",
    rarity: "COMMON",
    cardType: "CHARACTER",
    attack: 2,
    health: 1,
    size: 1,
    aura: 1,
    category: "AMERICAN",
    imageUrl: "/card-art/tyler-robinson.webp",
    abilityData: [
      {
        id: "tyler-robinson-only-counter",
        label: "Only Counter",
        trigger: "ACTIVATED",
        requiresTarget: true,
        effects: [
          { type: "DESTROY", target: "ENEMY_CHARACTER", cardSlug: "charlie-kirk" },
          { type: "DESTROY", target: "SELF" },
        ],
      },
    ],
  },
  zeroStatCard("charlie-kirk", "Charlie Kirk", "EPIC", "CHARACTER", "AMERICAN"),
  zeroStatCard("ada-printa", "ada printa", "COMMON", "CHARACTER"),
  zeroStatCard("eth22", "eth22", "RARE", "CHARACTER"),
  zeroStatCard("frenchplaty", "frenchplaty", "RARE", "CHARACTER"),
  zeroStatCard("tweeku", "tweeku", "RARE", "CHARACTER"),
  zeroStatCard("mwyi-inactive", "mwyi (inactive)", "MYTHIC", "CHARACTER"),
  {
    ...zeroStatCard("vanessa", "Vanessa", "EPIC", "CHARACTER", "AMERICAN"),
    abilityData: [
      {
        id: "vanessa-heartbroken",
        label: "Heartbroken",
        trigger: "ACTIVATED",
        requiresTarget: false,
        cooldownTurns: 3,
        conditions: [
          { type: "LEADER_IS", cardSlugs: ["garrett-current", "garrett-prime"] },
        ],
        effects: [
          { type: "BUFF_ATTACK", target: "SELF", amount: 3, duration: "PERMANENT" },
        ],
      },
    ],
  },
  zeroStatCard("the1nutbandit", "the1nutbandit", "ULTRA_LEGENDARY", "CHARACTER"),
  zeroStatCard("pacmanpowerghost", "pacmanpowerghost", "RARE", "CHARACTER"),
  zeroStatCard("kyu-sugardust", "Kyu Sugardust", "COMMON", "CHARACTER"),
  zeroStatCard("benjamin-netanyahu", "Benjamin Netanyahu", "COMMON", "CHARACTER"),
  zeroStatCard("tahm-kench", "Tahm Kench", "COMMON", "CHARACTER"),
  zeroStatCard("necrps-drunken-dad", "necrps drunken dad", "MYTHIC", "CHARACTER", "BASED"),
  {
    slug: "gabriela-stein",
    name: "Gabriela Stein",
    description: "Rare, steady, and aggressively mid.",
    flavorText: "Nothing crazy, nothing useless.",
    rarity: "RARE",
    cardType: "CHARACTER",
    attack: 4,
    health: 4,
    size: 3,
    aura: 3,
    imageUrl: "/card-art/gabriela-stein.webp",
    abilityData: [],
  },
  zeroStatCard("the-group-chat", "the Group Chat", "RARE", "BUILDING"),
  zeroStatCard("hunie-pop-speedrunning", "Hunie Pop Speedrunning", "COMMON", "BUILDING"),
  zeroStatCard("huniepotheads", "HuniePotHeads", "RARE", "BUILDING"),
  zeroStatCard("poland", "Poland", "EPIC", "BUILDING"),
  zeroStatCard("florida", "Florida", "EPIC", "BUILDING", "AMERICAN"),
  zeroStatCard("texas", "Texas", "EPIC", "BUILDING", "AMERICAN"),
  {
    ...zeroStatCard("jpjs-basement", "jpjs Basement", "MYTHIC", "BUILDING"),
    abilityData: [
      {
        id: "jpjs-basement-trap",
        label: "Trap",
        trigger: "ACTIVATED",
        requiresTarget: true,
        cooldownTurns: 3,
        conditions: [
          { type: "CARD_IN_HAND", cardSlug: "jpj" },
        ],
        effects: [
          { type: "STUN", target: "ENEMY_CHARACTER", amount: 3, duration: "TURN" },
        ],
      },
    ],
  },
  zeroStatCard("white-monster", "White Monster", "RARE", "ITEM", "BASED"),
  zeroStatCard("the-bong", "The Bong", "LEGENDARY", "ITEM", "AMERICAN"),
  zeroStatCard("assault-rifle", "assault rifle", "EPIC", "ITEM", "AMERICAN"),
  zeroStatCard("zubr-beer", "zubr beer", "MYTHIC", "ITEM", "BASED"),
];

export function getCardBySlug(slug: string) {
  return cardCatalog.find((card) => card.slug === slug);
}
