insert into public.card_templates (
  slug,
  name,
  description,
  rarity,
  card_type,
  attack,
  health,
  size,
  aura,
  image_url,
  sound_effect_url,
  flavor_text,
  ability_data,
  balance_version,
  category,
  drop_enabled
)
values
  (
    'ada-printa-chapter-2-leader',
    'Ada Printa (Chapter 2 Leader)',
    'A story-only leader version of Ada Printa.',
    'EPIC',
    'LEADER',
    9,
    16,
    5,
    9,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/ada-printa.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/ada-printa.mp3',
    'Printer warmed up. Bad sign.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_BOSS',
    false
  ),
  (
    'eth22-chapter-2-leader',
    'eth22 (Chapter 2 Leader)',
    'A story-only leader version of eth22.',
    'MYTHIC',
    'LEADER',
    10,
    20,
    5,
    10,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/eth22.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/eth22.mp3',
    'The second path gets uglier.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_BOSS',
    false
  ),
  (
    'mwyi-corrupted-chapter-2-leader',
    'mwyi (corrupted)',
    'A story-only corrupted leader version of mwyi.',
    'DIVINE',
    'LEADER',
    11,
    26,
    6,
    11,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/mwyi.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/mwyi.mp3',
    'The 50/50 stopped being funny.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_BOSS',
    false
  ),
  (
    'vanessa-chapter-2-leader',
    'Vanessa (Chapter 2 Leader)',
    'A story-only leader version of Vanessa.',
    'DIVINE',
    'LEADER',
    12,
    32,
    7,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/vanessa.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/vanessa.mp3',
    'Heartbreak became a win condition.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_BOSS',
    false
  ),
  (
    'woke-mind-virus-ascended-story-leader',
    'The Woke Mind Virus (Ascended)',
    'A stronger rematch version of the final boss.',
    'DIVINE',
    'LEADER',
    14,
    42,
    8,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/woke-mind-virus.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/woke-mind-virus.mp3',
    'It learned from the first loss.',
    '[{"id":"woke-mind-virus-total-brainrot","label":"Total Brainrot","trigger":"ACTIVATED","requiresTarget":false,"cooldownTurns":2,"effects":[{"type":"DAMAGE","target":"ENEMY_BOARD_CHARACTERS","amount":7},{"type":"BLIND","target":"ENEMY_CHARACTER","amount":1,"duration":"TURN"},{"type":"BUFF_ATTACK","target":"SELF","amount":2,"duration":"PERMANENT"}]}]'::jsonb,
    'story-2.0',
    'STORY_BOSS',
    false
  ),
  (
    'ada-printa-chapter-2-reward',
    'Ada Printa (Chapter 2 Reward)',
    'A story reward character version of Ada Printa.',
    'EPIC',
    'CHARACTER',
    5,
    5,
    3,
    4,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/ada-printa.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/ada-printa.mp3',
    'Still printing problems.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_REWARD',
    false
  ),
  (
    'eth22-chapter-2-reward',
    'eth22 (Chapter 2 Reward)',
    'A story reward character version of eth22.',
    'MYTHIC',
    'CHARACTER',
    8,
    6,
    4,
    5,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/eth22.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/eth22.mp3',
    'Reduced from boss threat to deck problem.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_REWARD',
    false
  ),
  (
    'mwyi-corrupted-chapter-2-reward',
    'mwyi (corrupted reward)',
    'A story reward character version of corrupted mwyi.',
    'DIVINE',
    'CHARACTER',
    9,
    8,
    5,
    7,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/mwyi.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/mwyi.mp3',
    'You probably should not keep this, but you can.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_REWARD',
    false
  ),
  (
    'vanessa-chapter-2-reward',
    'Vanessa (Chapter 2 Reward)',
    'A story reward character version of Vanessa.',
    'DIVINE',
    'CHARACTER',
    8,
    10,
    6,
    6,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/vanessa.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/vanessa.mp3',
    'A little less boss, still a lot.',
    '[]'::jsonb,
    'story-2.0',
    'STORY_REWARD',
    false
  ),
  (
    'woke-mind-virus-deployable',
    'Woke Mind Virus (Deployable)',
    'A risky global item that empowers every friendly card currently in play.',
    'DIVINE',
    'ITEM',
    0,
    0,
    0,
    0,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/woke-mind-virus.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/sounds/woke-mind-virus.mp3',
    'Power, with a tiny chance of catastrophic brainrot.',
    '[{"id":"woke-mind-virus-deploy","label":"Deploy Brainrot","trigger":"ON_PLAY","requiresTarget":false,"effects":[{"type":"BUFF_ATTACK","target":"FRIENDLY_BOARD_AND_LEADER","amount":2,"duration":"PERMANENT"},{"type":"BUFF_HEALTH","target":"FRIENDLY_BOARD_AND_LEADER","amount":4,"duration":"PERMANENT"},{"type":"BUFF_AURA","target":"FRIENDLY_BOARD_AND_LEADER","amount":2,"duration":"PERMANENT"},{"type":"CHANCE_DESTROY","target":"FRIENDLY_BOARD_AND_LEADER","chance":0.05}]}]'::jsonb,
    'story-2.0',
    'STORY_REWARD',
    false
  )
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  rarity = excluded.rarity,
  card_type = excluded.card_type,
  attack = excluded.attack,
  health = excluded.health,
  size = excluded.size,
  aura = excluded.aura,
  image_url = excluded.image_url,
  sound_effect_url = excluded.sound_effect_url,
  flavor_text = excluded.flavor_text,
  ability_data = excluded.ability_data,
  balance_version = excluded.balance_version,
  category = excluded.category,
  drop_enabled = excluded.drop_enabled;
