insert into public.card_templates (
  slug,
  name,
  description,
  rarity,
  card_type,
  attack,
  health,
  size,
  aura,
  image_url,
  sound_effect_url,
  flavor_text,
  ability_data,
  balance_version,
  category,
  drop_enabled
)
values
  (
    'woke-charlie-kirk-chapter-3-leader',
    'Woke Charlie Kirk',
    'A story-only leader version of Charlie Kirk after the algorithm got to him.',
    'DIVINE',
    'LEADER',
    13,
    44,
    8,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/woke-charlie-kirk-chapter-3-leader.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/woke-charlie-kirk-chapter-3-leader.mp3',
    'The talking points started talking back.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'king-von-chapter-3-leader',
    'King Von',
    'A story-only leader with direct pressure and a heavier deck behind him.',
    'DIVINE',
    'LEADER',
    14,
    46,
    8,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/king-von-chapter-3-leader.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/king-von-chapter-3-leader.mp3',
    'Chapter 3 stopped warming up.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'shrekel-not-in-poland-chapter-3-leader',
    'Shrekel (not in Poland)',
    'A story-only leader that is explicitly not in Poland and still somehow a problem.',
    'DIVINE',
    'LEADER',
    14,
    48,
    9,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/shrekel-not-in-poland-chapter-3-leader.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/shrekel-not-in-poland-chapter-3-leader.mp3',
    'Wrong swamp. Correct danger.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'kanye-west-chapter-3-leader',
    'Kanye West',
    'A story-only leader who can briefly become YE, then pays for the crash after.',
    'DIVINE',
    'LEADER',
    12,
    45,
    7,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/kanye-west-chapter-3-leader.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/kanye-west-chapter-3-leader.mp3',
    'One round of genius. Then the invoice.',
    '[{"id":"kanye-west-become-ye","label":"Become YE","trigger":"ACTIVATED","requiresTarget":false,"oncePerGame":true,"effects":[{"type":"TEMP_TRANSFORM","target":"SELF","metadata":{"ownerTurns":1,"attack":8,"health":15,"aura":3,"afterAttack":-3,"afterHealth":-8,"afterAura":-1}}]}]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'suicide-bomber-chapter-3-leader',
    'Suicide Bomber',
    'A story-only leader that detonates once when it survives at critical health.',
    'DIVINE',
    'LEADER',
    8,
    50,
    9,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/suicide-bomber-chapter-3-leader.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/suicide-bomber-chapter-3-leader.mp3',
    'The board state becomes a crater.',
    '[{"id":"suicide-bomber-critical-detonation","label":"Critical Detonation","trigger":"ON_DAMAGED","oncePerGame":true,"requiresTarget":false,"conditions":[{"type":"SELF_HEALTH_BELOW","value":20}],"effects":[{"type":"DESTROY","target":"ALL_IN_PLAY_EXCEPT_SELF"}]}]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'anarchy-gluttonous-chapter-3-leader',
    'Anarchy (Gluttonous)',
    'Anarchy, but even fatter. A final boss that eats board cards to become harder to kill.',
    'DIVINE',
    'LEADER',
    15,
    62,
    10,
    12,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/anarchy-gluttonous-chapter-3-leader.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/anarchy-gluttonous-chapter-3-leader.mp3',
    'The buffet fought back and lost.',
    '[{"id":"anarchy-gluttonous-devour","label":"Devour","trigger":"ACTIVATED","requiresTarget":true,"cooldownTurns":3,"effects":[{"type":"CONSUME","target":"ENEMY_BOARD_CARD"}]}]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'necrps-very-drunken-dad',
    'necrps very drunken dad',
    'A story-only support card that makes late Chapter 3 decks less polite.',
    'DIVINE',
    'CHARACTER',
    11,
    18,
    9,
    10,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/necrps-very-drunken-dad.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/necrps-very-drunken-dad.mp3',
    'Somehow even more hammered.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_BOSS',
    false
  ),
  (
    'woke-charlie-kirk-chapter-3-reward',
    'Woke Charlie Kirk (Chapter 3 Reward)',
    'A story reward character version of Woke Charlie Kirk.',
    'DIVINE',
    'CHARACTER',
    8,
    8,
    4,
    6,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/woke-charlie-kirk-chapter-3-reward.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/woke-charlie-kirk-chapter-3-reward.mp3',
    'A smaller contradiction.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_REWARD',
    false
  ),
  (
    'king-von-chapter-3-reward',
    'King Von (Chapter 3 Reward)',
    'A story reward character version of King Von.',
    'DIVINE',
    'CHARACTER',
    9,
    9,
    5,
    7,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/king-von-chapter-3-reward.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/king-von-chapter-3-reward.mp3',
    'Lower stakes. Still pressure.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_REWARD',
    false
  ),
  (
    'shrekel-not-in-poland-chapter-3-reward',
    'Shrekel (not in Poland Reward)',
    'A story reward character version of Shrekel.',
    'DIVINE',
    'CHARACTER',
    8,
    12,
    6,
    7,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/shrekel-not-in-poland-chapter-3-reward.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/shrekel-not-in-poland-chapter-3-reward.mp3',
    'Still not in Poland.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_REWARD',
    false
  ),
  (
    'kanye-west-chapter-3-reward',
    'Kanye West (Chapter 3 Reward)',
    'A story reward character version of Kanye West.',
    'DIVINE',
    'CHARACTER',
    8,
    8,
    4,
    7,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/kanye-west-chapter-3-reward.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/kanye-west-chapter-3-reward.mp3',
    'The crash is still included.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_REWARD',
    false
  ),
  (
    'suicide-bomber-chapter-3-reward',
    'Suicide Bomber (Chapter 3 Reward)',
    'A story reward character version of Suicide Bomber.',
    'DIVINE',
    'CHARACTER',
    7,
    10,
    5,
    7,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/suicide-bomber-chapter-3-reward.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/suicide-bomber-chapter-3-reward.mp3',
    'Less blast radius. Still suspicious.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_REWARD',
    false
  ),
  (
    'anarchy-gluttonous-chapter-3-reward',
    'Anarchy (Gluttonous Reward)',
    'A story reward character version of Anarchy (Gluttonous).',
    'DIVINE',
    'CHARACTER',
    10,
    13,
    6,
    8,
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/cards/anarchy-gluttonous-chapter-3-reward.webp',
    'https://ibhtgdxruglejkpslqgx.supabase.co/storage/v1/object/public/card-art/sounds/anarchy-gluttonous-chapter-3-reward.mp3',
    'Still hungry, but playable.',
    '[]'::jsonb,
    'story-3.0',
    'STORY_REWARD',
    false
  )
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  rarity = excluded.rarity,
  card_type = excluded.card_type,
  attack = excluded.attack,
  health = excluded.health,
  size = excluded.size,
  aura = excluded.aura,
  image_url = excluded.image_url,
  sound_effect_url = excluded.sound_effect_url,
  flavor_text = excluded.flavor_text,
  ability_data = excluded.ability_data,
  balance_version = excluded.balance_version,
  category = excluded.category,
  drop_enabled = excluded.drop_enabled;
